### Announce
POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "code": "JAVAX-DDD2",
  "title": "Domain Driven Design2",
  "limit": 5
}

### Enroll
PUT http://localhost:8080/api/courses/2/enrollments
Content-Type: application/json

{
  "courseId": 2,
  "employeeId": 2
}

### Find all courses
GET http://localhost:8080/api/courses

### Join
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "John Doe"
}

### Find all employees
GET http://localhost:8080/api/employees

### Leave
DELETE http://localhost:8080/api/employees/2