spring.application.name=javax-ddd-training-2026-09-24

spring.datasource.url=jdbc:postgresql://localhost:5432/courses
spring.datasource.username=courses
spring.datasource.password=courses

spring.jpa.generate-ddl=true
spring.jpa.open-in-view=false